version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Cleaning any existing dependencies..."
      - rm -rf python/  # Remove any previously installed dependencies
      - mkdir -p python
      - echo "Installing Pandas (with NumPy) for AWS Lambda..."
      - pip install --platform manylinux2014_x86_64 --only-binary=:all: --no-cache-dir -r requirements.txt -t python/
      - echo "Dependencies installed. Listing contents:"
      - ls -l python/

  build:
    commands:
      - echo "Zipping dependency package for Lambda Layer..."
      - zip -r9 dependencies_layer.zip python
      - echo "Dependency layer zip created."
      - ls -lh dependencies_layer.zip

      - echo "Zipping Lambda function package..."
      - zip -r9 lambda_function.zip lambda_function.py
      - echo "Lambda function zip created."
      - ls -lh lambda_function.zip

  post_build:
    commands:
      - echo "Publishing new Lambda Layer version..."
      - |
        LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name lambda-dependencies-layer \
          --zip-file fileb://dependencies_layer.zip \
          --compatible-runtimes python3.11 \
          --query Version --output text --region us-east-2)
        echo "Published Lambda Layer Version: $LAYER_VERSION"
